# Generated by Django 3.1.4 on 2020-12-31 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201231_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='facebook_limk',
            new_name='facebook_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='instagram_limk',
            new_name='instagram_link',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter_limk',
            new_name='twitter_link',
        ),
    ]
