# Generated by Django 3.1.4 on 2021-01-17 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20210104_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='vin',
            new_name='vin_no',
        ),
    ]
